server:
  port: 8205
spring:
  application:
    name: service-sms
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  redis:
    host: 192.168.18.133
    port: 6379
    database: 0
    timeout: 1800000
    lettuce:
      pool:
        max-active: 20
        max-wait: -1 #最大阻塞等待时间(负数表示没限制)
        max-idle: 5
        min-idle: 0

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

  #rabbitmq地址
  rabbitmq:
    password: guest
    username: guest
    host: 192.168.18.133
    port: 5672

# 容联云中测试参数
cloopen:
  sms:
    url: app.cloopen.com
    port: 8883
    accountSid: 8aaf07087e7b9872017e86514329014c
    accountToken: e39f3bc410074150b2dd4228d1935409
    appId: 8aaf07087e7b9872017e865144660152
